---
title: "Guide to Postdocs in Econ/Management"
author: ''
date: '2022-02-12'
slug: postdoc-faq
draft: false
categories:
  - Economics
tags:
  - postdocs
  - faq
header:
  caption: ''
  image: ''
output:
  blogdown::html_page:
    toc: true
summary: 'A quick guide to Econ Postdocs'
---

Hi! We wrote this post to help prospective postdocs, current postdocs, or even people who want to hire postdocs understand what it's like doing a postdoc in economics (and similar fields like management) is like. Please treat it as a *living document* that will evolve as we get feedback and better information.^[Original authors of this post are [Valerie Bostwick](https://vkbostwick.weebly.com/), [Sarah Bana](http://www.sarahbana.com/), and [Wei Yang Tham](https://wytham.rbind.io/). Thanks to [Kirby Nielsen](https://kirbyknielsen.com/) for helpful contributions to this guide.] Note that this is currently a very US-centric guide, but it's the system we know best (and even then there's a lot we don't know!)


## What is a postdoc?

The NSF and NIH define a postdoc as "an individual who has received a doctoral degree (or equivalent) and is engaged in a temporary and defined period of mentored advanced training to enhance the professional skills and research independence needed to pursue his or her chosen career path." This is not a bad definition but still kinda vague, so let's try to get more specific.

In economics, what this basically means is you work for 2-3 years with a mentor with the expectation that this prepares you to go on the market for your next job.^[For the rest of the document, we're gonna use "economics" to refer to economics and econ-adjacent fields, rather than saying "economics/management/..." over and over again.] 

Here's a rough taxonomy of econ postdocs: 

1. "Standard" postdoc: hired to work on a specific project or at least projects in a certain domain (and will have to go on the market again!)
1. Postdocs that are more like fellowships: for people who already have jobs lined up and basically get an extra year or so to work on their own on whatever they want.
1. Anything else in-between, including but not limited to: you're hired to work on specific areas or with specific people but you also have a job lined up once the postdoc is over; or you're hired by a department but not a specific supervisor within the department

The first kind of postdoc ("standard") is the one we have mind as we're writing this, but different parts of the guide will have some relevance to other kinds of postdocs.

## What do postdocs in economics earn?

If you know of good data on this, let us know! 

We tried using the Survey of Doctorate Recipients public use data (pooling 2015, 2017, 2019 waves), which returns an average of $60,000, but that's based on 57 observations. 

Based on the SDR and informal knowledge, *our current best guess is that a typical econ postdoc salary is in the range of $60-65,000*, but we'd love to hear if you think that's inaccurate. 

## What benefits do postdocs get?

This is even trickier than salaries. Benefits are gonna depend on how your specific university classifies postdocs. If postdocs are classified as staff, then you'll have staff benefits and pay the same insurance premiums and get 401(k) matching. If postdocs are classified as a student or "student-adjacent", you might receive different benefits like student loan deferment and not having to pay health insurance premiums, but you might also miss out on other perks that staff get. 

In short, you should ask about this. 

## What visa do I use (for non-US citizens)?

(Usual disclaimer that we aren't immigration lawyers. Triple check all this with your school's international affairs office and/or actual immigration law experts)

If you're already in the US on an F1 visa, the most straightforward route is probably to use your OPT (1 year), and then the STEM OPT extension (2 more years). Otherwise, postdocs usually use the J1 visa

## I got a postdoc offer. Should I negotiate?

Yes. 

We don't have much to say about how to do it, but as with any job offer, it's your prerogative to negotiate. Even if you don't think you have much bargaining power, sometimes just asking is surprisingly effective.^[This also applies to getting a better deal on your internet package.] 

## I'm thinking of taking a postdoc. What factors should I consider or negotiate over?

Here's a list of some things to consider asking your prospective supervisor about. A guiding principle here is to think about what you'll need to be a stronger candidate when you go on the market at the end of your postdoc. 

### Extending the postdoc
Ideally, you'll finish your postdoc and go off to your fancy new job in no time! But sometimes stuff goes wrong (maybe a project doesn't work out or there's a pandemic) so it's worth asking early on what the possibilites of extending the postdoc are. There's a decent chance your supervisor can't give a definitive answer, but you might still gain valuable information (e.g. are they thinking of applying for more funding?)

### Responsibilities 
Some postdocs are set up such that you’re working on a specific project. What percentage of your time are you expected to devote to that project versus your own projects? Does that project have a fixed timeline? If something happens to that project, will you still be funded?

### Authorship
How will authorship be decided? Will there be opportunities to carve out your own "slice" of the project (especially if the main project you're working on will have many authors)? 

### Teaching
This could work either way. Some postdocs involve teaching, so you'll want to find out if that is so and how much work it will involve. Or you might want to do some teaching, perhaps because you didn't have much teaching experience in grad school. If so, it's worth asking if there might be opportunies to do that.

### Research Support
What kind of financial support can you get to do research and build your network? Items you might want to ask about include:

- Conference expenses (travel, registration fees)
- Journal submission fees
- Computing equipment

### Can you be a PI on a grant?

At some point in your postdoc, you may want to apply for and manage your own grant funding as the Principal Investigator. The ease of doing may be different across institutions. At some places it might be straightforward or the institution at least provides a clear path towards enabling that to happen, while at others it may be a bureaucratically challenging endeavor. 

### Relationship with supervisor
- What is your supervisor's mentoring style? How often will you be able to get on their calendar?
- Who else are you reporting to?

### Relationship with department
Postdocs are in a bit of a weird position. You don't enter with a cohort of classmates like in undergrad or grad school but you're not faculty either. Some things you might want to know are: 

- Where is your office? Is it in the same building as people you want to know?
- Can you attend seminars?
- Can you present in the dept seminar?

### What's the "lab" like?

If you're being hired as part of a lab or research group, what is the culture of the lab like? How do members of the lab support each other in their research? Ask to speak to a current grad student or postdoc at the lab about their experience.

### Moving costs
Can your supervisor or department help with moving costs in any way? Even if they can't cover all your moving expenses, there may be little things they can do to ease the transition like flying you out in advance to look for housing.

## Going on the market...again!

### Do I need a new Job Market Paper?
Yes. The only situation where we're not as sure this applies is if you do a 1-year postdoc i.e. go on consecutive markets

### Do I need publications or R&Rs?
It's not necessarily the end of the world if you don't, but of course it would help a lot. 

### Who is going to write your rec letters? 
Presumably your postdoc supervisor will be one of them, but you might also want one of your old letter writers (say, your advisor) to write one again. In that case, make an effort to keep them updated on your progress. 

### How will your supervisor support your job search?

- What kind of administrative support can you get from the department or will you rely on your old department?
- Are they ok with you spending paid time to apply to jobs, go to interviews, do flyouts, etc., even if your job market paper is unrelated to the postdoc?
- Is your supervisor supportive of the type of jobs you are looking for? (academia vs industry, different types of jobs within academia)






